// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAllianceTech = "alliance_tech"

// AllianceTech mapped from table <alliance_tech>
type AllianceTech struct {
	ID           string    `gorm:"column:id;primaryKey" json:"id"`
	TechType     string    `gorm:"column:tech_type;not null" json:"tech_type"`
	Level        int32     `gorm:"column:level;not null;default:1" json:"level"`
	Bonus        int32     `gorm:"column:bonus;not null" json:"bonus"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
	UpgradeWood  int32     `gorm:"column:upgrade_wood;not null;default:500" json:"upgrade_wood"`
	UpgradeStone int32     `gorm:"column:upgrade_stone;not null;default:400" json:"upgrade_stone"`
	UpgradeIron  int32     `gorm:"column:upgrade_iron;not null;default:300" json:"upgrade_iron"`
	UpgradeFood  int32     `gorm:"column:upgrade_food;not null;default:1000" json:"upgrade_food"`
	UpgradeGold  int32     `gorm:"column:upgrade_gold;not null;default:50" json:"upgrade_gold"`
	UpgradeTime  int32     `gorm:"column:upgrade_time;not null;default:1500" json:"upgrade_time"`
	AllianceID   string    `gorm:"column:alliance_id;not null" json:"alliance_id"`
}

// TableName AllianceTech's table name
func (*AllianceTech) TableName() string {
	return TableNameAllianceTech
}
