// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAlliance = "alliance"

// Alliance mapped from table <alliance>
type Alliance struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	Level              int32     `gorm:"column:level;not null;default:1" json:"level"`
	MemberLimit        int32     `gorm:"column:member_limit;not null;default:50" json:"member_limit"`
	CurrentMembers     int32     `gorm:"column:current_members;not null;default:1" json:"current_members"`
	Description        string    `gorm:"column:description" json:"description"`
	CreatedAt          time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
	TroopsRequest      int32     `gorm:"column:troops_request;not null" json:"troops_request"`
	BlockRequest       bool      `gorm:"column:block_request;not null" json:"block_request"`
	BlockRequestTime   int32     `gorm:"column:block_request_time" json:"block_request_time"`
	AllianceResourceID string    `gorm:"column:alliance_resource_id" json:"alliance_resource_id"`
	UpgradeWood        int32     `gorm:"column:upgrade_wood;not null;default:1000" json:"upgrade_wood"`
	UpgradeStone       int32     `gorm:"column:upgrade_stone;not null;default:800" json:"upgrade_stone"`
	UpgradeIron        int32     `gorm:"column:upgrade_iron;not null;default:500" json:"upgrade_iron"`
	UpgradeFood        int32     `gorm:"column:upgrade_food;not null;default:2000" json:"upgrade_food"`
	UpgradeGold        int32     `gorm:"column:upgrade_gold;not null;default:100" json:"upgrade_gold"`
	UpgradeTime        int32     `gorm:"column:upgrade_time;not null;default:7200" json:"upgrade_time"`
}

// TableName Alliance's table name
func (*Alliance) TableName() string {
	return TableNameAlliance
}
