// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAllianceContributionRecord = "alliance_contribution_records"

// AllianceContributionRecord mapped from table <alliance_contribution_records>
type AllianceContributionRecord struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	AllianceID string    `gorm:"column:alliance_id;not null" json:"alliance_id"`
	MemberID   string    `gorm:"column:member_id;not null" json:"member_id"`
	Wood       int32     `gorm:"column:wood;not null" json:"wood"`
	Stone      int32     `gorm:"column:stone;not null" json:"stone"`
	Iron       int32     `gorm:"column:iron;not null" json:"iron"`
	Food       int32     `gorm:"column:food;not null" json:"food"`
	Gold       int32     `gorm:"column:gold;not null" json:"gold"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AllianceContributionRecord's table name
func (*AllianceContributionRecord) TableName() string {
	return TableNameAllianceContributionRecord
}
