// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAllianceResource = "alliance_resource"

// AllianceResource mapped from table <alliance_resource>
type AllianceResource struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	AllianceID string    `gorm:"column:alliance_id;not null" json:"alliance_id"`
	Wood       int32     `gorm:"column:wood;not null" json:"wood"`
	Stone      int32     `gorm:"column:stone;not null" json:"stone"`
	Iron       int32     `gorm:"column:iron;not null" json:"iron"`
	Food       int32     `gorm:"column:food;not null" json:"food"`
	Gold       int32     `gorm:"column:gold;not null" json:"gold"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AllianceResource's table name
func (*AllianceResource) TableName() string {
	return TableNameAllianceResource
}
