// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAllianceRequest = "alliance_request"

// AllianceRequest mapped from table <alliance_request>
type AllianceRequest struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	AllianceID string    `gorm:"column:alliance_id;not null" json:"alliance_id"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	Status     string    `gorm:"column:status;not null;default:PENDING" json:"status"`
	HandlerID  string    `gorm:"column:handler_id" json:"handler_id"`
}

// TableName AllianceRequest's table name
func (*AllianceRequest) TableName() string {
	return TableNameAllianceRequest
}
