// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAllianceMember = "alliance_member"

// AllianceMember mapped from table <alliance_member>
type AllianceMember struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	AllianceID string    `gorm:"column:alliance_id;not null" json:"alliance_id"`
	Position   string    `gorm:"column:position;not null;default:MEMBER" json:"position"`
	JoinedAt   time.Time `gorm:"column:joined_at;not null;default:CURRENT_TIMESTAMP" json:"joined_at"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AllianceMember's table name
func (*AllianceMember) TableName() string {
	return TableNameAllianceMember
}
