// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBlackList = "black_list"

// BlackList mapped from table <black_list>
type BlackList struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	IP        string    `gorm:"column:ip;not null" json:"ip"`
	UserID    string    `gorm:"column:user_id;not null" json:"user_id"`
	Reason    string    `gorm:"column:reason;not null" json:"reason"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName BlackList's table name
func (*BlackList) TableName() string {
	return TableNameBlackList
}
