// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingHarem = "building_harem"

// BuildingHarem mapped from table <building_harem>
type BuildingHarem struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Capacity   int32     `gorm:"column:capacity;not null;default:10" json:"capacity"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID     string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingHarem's table name
func (*BuildingHarem) TableName() string {
	return TableNameBuildingHarem
}
