// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingWall = "building_wall"

// BuildingWall mapped from table <building_wall>
type BuildingWall struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Defense    int32     `gorm:"column:defense;not null;default:15" json:"defense"`
	Durability int32     `gorm:"column:durability;not null;default:1500" json:"durability"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID     string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingWall's table name
func (*BuildingWall) TableName() string {
	return TableNameBuildingWall
}
