// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingResource = "building_resource"

// BuildingResource mapped from table <building_resource>
type BuildingResource struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Level       int32     `gorm:"column:level;not null;default:1" json:"level"`
	Yield       int32     `gorm:"column:yield;not null;default:500" json:"yield"`
	Scale       int32     `gorm:"column:scale;not null" json:"scale"`
	Wood        int32     `gorm:"column:wood;not null" json:"wood"`
	Iron        int32     `gorm:"column:iron;not null" json:"iron"`
	Stone       int32     `gorm:"column:stone;not null" json:"stone"`
	Food        int32     `gorm:"column:food;not null" json:"food"`
	Gold        int32     `gorm:"column:gold;not null" json:"gold"`
	UpgradeTime int32     `gorm:"column:upgrade_time;not null" json:"upgrade_time"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	UserID      string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID      string    `gorm:"column:city_id;not null" json:"city_id"`
}

// TableName BuildingResource's table name
func (*BuildingResource) TableName() string {
	return TableNameBuildingResource
}
