// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingWarehouse = "building_warehouse"

// BuildingWarehouse mapped from table <building_warehouse>
type BuildingWarehouse struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Capacity   int32     `gorm:"column:capacity;not null;default:50" json:"capacity"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID     string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingWarehouse's table name
func (*BuildingWarehouse) TableName() string {
	return TableNameBuildingWarehouse
}
