// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingBarrack = "building_barracks"

// BuildingBarrack mapped from table <building_barracks>
type BuildingBarrack struct {
	ID                     string    `gorm:"column:id;primaryKey" json:"id"`
	CanRecruitInfantry     bool      `gorm:"column:can_recruit_infantry;not null;default:true" json:"can_recruit_infantry"`
	CanRecruitLightCavalry bool      `gorm:"column:can_recruit_light_cavalry;not null" json:"can_recruit_light_cavalry"`
	CanRecruitHeavyCavalry bool      `gorm:"column:can_recruit_heavy_cavalry;not null" json:"can_recruit_heavy_cavalry"`
	CanRecruitArcher       bool      `gorm:"column:can_recruit_archer;not null" json:"can_recruit_archer"`
	CanRecruitCrossbowmen  bool      `gorm:"column:can_recruit_crossbowmen;not null" json:"can_recruit_crossbowmen"`
	CanRecruitScout        bool      `gorm:"column:can_recruit_scout;not null" json:"can_recruit_scout"`
	CanRecruitCatapult     bool      `gorm:"column:can_recruit_catapult;not null" json:"can_recruit_catapult"`
	CreatedAt              time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID             string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID                 string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID                 string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingBarrack's table name
func (*BuildingBarrack) TableName() string {
	return TableNameBuildingBarrack
}
