// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuilding = "building"

// Building mapped from table <building>
type Building struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Type        string    `gorm:"column:type;not null" json:"type"`
	Level       int32     `gorm:"column:level;not null;default:1" json:"level"`
	CityID      string    `gorm:"column:city_id;not null" json:"city_id"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
	Wood        int32     `gorm:"column:wood;not null" json:"wood"`
	Stone       int32     `gorm:"column:stone;not null" json:"stone"`
	Iron        int32     `gorm:"column:iron;not null" json:"iron"`
	Food        int32     `gorm:"column:food;not null" json:"food"`
	Gold        int32     `gorm:"column:gold;not null" json:"gold"`
	Scale       int32     `gorm:"column:scale;not null" json:"scale"`
	UpgradeTime int32     `gorm:"column:upgrade_time;not null" json:"upgrade_time"`
}

// TableName Building's table name
func (*Building) TableName() string {
	return TableNameBuilding
}
