// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingAdministration = "building_administration"

// BuildingAdministration mapped from table <building_administration>
type BuildingAdministration struct {
	ID                     string    `gorm:"column:id;primaryKey" json:"id"`
	ResourcePointsCapacity int32     `gorm:"column:resource_points_capacity;not null;default:1" json:"resource_points_capacity"`
	CreatedAt              time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt              time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID             string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID                 string    `gorm:"column:user_id;not null" json:"user_id"`
	MapElementID           string    `gorm:"column:map_element_id;not null" json:"map_element_id"`
	CityID                 string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingAdministration's table name
func (*BuildingAdministration) TableName() string {
	return TableNameBuildingAdministration
}
