// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBuildingCommercial = "building_commercial"

// BuildingCommercial mapped from table <building_commercial>
type BuildingCommercial struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Prosperity int32     `gorm:"column:prosperity;not null;default:20" json:"prosperity"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	BuildingID string    `gorm:"column:building_id;not null" json:"building_id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	CityID     string    `gorm:"column:cityId" json:"cityId"`
}

// TableName BuildingCommercial's table name
func (*BuildingCommercial) TableName() string {
	return TableNameBuildingCommercial
}
