// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCity = "city"

// City mapped from table <city>
type City struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	Name               string    `gorm:"column:name;not null" json:"name"`
	Population         int32     `gorm:"column:population;not null" json:"population"`
	OwnerID            string    `gorm:"column:owner_id;not null" json:"owner_id"`
	MapElementID       string    `gorm:"column:map_element_id;not null" json:"map_element_id"`
	CreatedAt          time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt          time.Time `gorm:"column:updated_at" json:"updated_at"`
	Food               int32     `gorm:"column:food;not null" json:"food"`
	Wood               int32     `gorm:"column:wood;not null" json:"wood"`
	Stone              int32     `gorm:"column:stone;not null" json:"stone"`
	Gold               int32     `gorm:"column:gold;not null" json:"gold"`
	Iron               int32     `gorm:"column:iron;not null" json:"iron"`
	Scale              int32     `gorm:"column:scale;not null" json:"scale"`
	PopulationUpdateAt time.Time `gorm:"column:population_update_at" json:"population_update_at"`
	GoldUpdateAt       time.Time `gorm:"column:gold_update_at" json:"gold_update_at"`
	ResourceUpdateAt   time.Time `gorm:"column:resource_update_at" json:"resource_update_at"`
}

// TableName City's table name
func (*City) TableName() string {
	return TableNameCity
}
