// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDropRate = "drop_rate"

// DropRate mapped from table <drop_rate>
type DropRate struct {
	ID        int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Business  string    `gorm:"column:business;not null" json:"business"`
	Category  string    `gorm:"column:category;not null" json:"category"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	DropRate  int32     `gorm:"column:drop_rate;not null" json:"drop_rate"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName DropRate's table name
func (*DropRate) TableName() string {
	return TableNameDropRate
}
