// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameLetter = "letter"

// Letter mapped from table <letter>
type Letter struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	Content    []uint8   `gorm:"column:content" json:"content"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
	ConsumerID string    `gorm:"column:consumer_id" json:"consumer_id"`
	SenderID   string    `gorm:"column:sender_id" json:"sender_id"`
	OwnerID    string    `gorm:"column:owner_id;not null" json:"owner_id"`
}

// TableName Letter's table name
func (*Letter) TableName() string {
	return TableNameLetter
}
