// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMapElement = "map_element"

// MapElement mapped from table <map_element>
type MapElement struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	Category         string    `gorm:"column:category;not null" json:"category"`
	Level            int32     `gorm:"column:level;not null;default:1" json:"level"`
	Experience       int32     `gorm:"column:experience;not null" json:"experience"`
	X                int32     `gorm:"column:x;not null" json:"x"`
	Y                int32     `gorm:"column:y;not null" json:"y"`
	OwnerID          string    `gorm:"column:owner_id" json:"owner_id"`
	Resource         int32     `gorm:"column:resource" json:"resource"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	CityID           string    `gorm:"column:city_id" json:"city_id"`
	AdministrationID string    `gorm:"column:administration_id" json:"administration_id"`
}

// TableName MapElement's table name
func (*MapElement) TableName() string {
	return TableNameMapElement
}
