// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMilitaryAction = "military_action"

// MilitaryAction mapped from table <military_action>
type MilitaryAction struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	Type              string    `gorm:"column:type;not null" json:"type"`
	RemainTime        int32     `gorm:"column:remain_time;not null" json:"remain_time"`
	CreatedAt         time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         time.Time `gorm:"column:updated_at" json:"updated_at"`
	OccupyTime        time.Time `gorm:"column:occupy_time" json:"occupy_time"`
	AttackerElementID string    `gorm:"column:attacker_element_id;not null" json:"attacker_element_id"`
	DefenderElementID string    `gorm:"column:defender_element_id;not null" json:"defender_element_id"`
	AttackerID        string    `gorm:"column:attacker_id;not null" json:"attacker_id"`
	DefenderID        string    `gorm:"column:defender_id" json:"defender_id"`
}

// TableName MilitaryAction's table name
func (*MilitaryAction) TableName() string {
	return TableNameMilitaryAction
}
