// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOfficer = "officer"

// Officer mapped from table <officer>
type Officer struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	Level            int32     `gorm:"column:level;not null;default:1" json:"level"`
	Experience       int32     `gorm:"column:experience;not null" json:"experience"`
	Defense          int32     `gorm:"column:defense;not null;default:1" json:"defense"`
	Attack           int32     `gorm:"column:attack;not null;default:1" json:"attack"`
	Health           int32     `gorm:"column:health;not null;default:1" json:"health"`
	Scout            int32     `gorm:"column:scout;not null;default:1" json:"scout"`
	Speed            int32     `gorm:"column:speed;not null;default:1" json:"speed"`
	Salary           int32     `gorm:"column:salary;not null;default:100" json:"salary"`
	IsEnlisted       bool      `gorm:"column:isEnlisted;not null" json:"isEnlisted"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	WomanID          string    `gorm:"column:woman_id;not null" json:"woman_id"`
	MapElementID     string    `gorm:"column:map_element_id;not null" json:"map_element_id"`
	MilitaryActionID string    `gorm:"column:military_action_id" json:"military_action_id"`
}

// TableName Officer's table name
func (*Officer) TableName() string {
	return TableNameOfficer
}
