// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRelation = "relation"

// Relation mapped from table <relation>
type Relation struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	FromUserID string    `gorm:"column:from_user_id;not null" json:"from_user_id"`
	ToUserID   string    `gorm:"column:to_user_id;not null" json:"to_user_id"`
	Relation   string    `gorm:"column:relation;not null" json:"relation"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Relation's table name
func (*Relation) TableName() string {
	return TableNameRelation
}
