// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSoldierType = "soldier_type"

// SoldierType mapped from table <soldier_type>
type SoldierType struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Attack      int32     `gorm:"column:attack;not null;default:10" json:"attack"`
	Defense     int32     `gorm:"column:defense;not null;default:10" json:"defense"`
	Health      int32     `gorm:"column:health;not null;default:100" json:"health"`
	Scout       int32     `gorm:"column:scout;not null;default:5" json:"scout"`
	Speed       int32     `gorm:"column:speed;not null;default:10" json:"speed"`
	Range       int32     `gorm:"column:range;not null;default:1" json:"range"`
	Capacity    int32     `gorm:"column:capacity;not null;default:10" json:"capacity"`
	Food        int32     `gorm:"column:food;not null;default:50" json:"food"`
	Wood        int32     `gorm:"column:wood;not null;default:100" json:"wood"`
	Iron        int32     `gorm:"column:iron;not null;default:50" json:"iron"`
	Stone       int32     `gorm:"column:stone;not null;default:50" json:"stone"`
	Gold        int32     `gorm:"column:gold;not null" json:"gold"`
	FoodConsume int32     `gorm:"column:food_consume;not null;default:1" json:"food_consume"`
	RecruitTime int32     `gorm:"column:recruit_time;not null;default:60" json:"recruit_time"`
	CreatedAt   time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName SoldierType's table name
func (*SoldierType) TableName() string {
	return TableNameSoldierType
}
