// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSoldier = "soldier"

// Soldier mapped from table <soldier>
type Soldier struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	Level            int32     `gorm:"column:level;not null;default:1" json:"level"`
	Experience       int32     `gorm:"column:experience;not null" json:"experience"`
	Quantity         int32     `gorm:"column:quantity;not null" json:"quantity"`
	Status           string    `gorm:"column:status;not null;default:IN_CITY" json:"status"`
	OwnerID          string    `gorm:"column:owner_id" json:"owner_id"`
	CityID           string    `gorm:"column:city_id" json:"city_id"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at" json:"updated_at"`
	MapElementID     string    `gorm:"column:map_element_id" json:"map_element_id"`
	SoldierTypeID    int32     `gorm:"column:soldier_type_id" json:"soldier_type_id"`
	MilitaryActionID string    `gorm:"column:military_action_id" json:"military_action_id"`
}

// TableName Soldier's table name
func (*Soldier) TableName() string {
	return TableNameSoldier
}
