// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWoman = "woman"

// Woman mapped from table <woman>
type Woman struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	Name            string    `gorm:"column:name;not null" json:"name"`
	Star            int32     `gorm:"column:star;not null" json:"star"`
	Charm           int32     `gorm:"column:charm;not null" json:"charm"`
	Figure          int32     `gorm:"column:figure;not null" json:"figure"`
	Height          int32     `gorm:"column:height;not null" json:"height"`
	Intelligence    int32     `gorm:"column:intelligence;not null" json:"intelligence"`
	Appearance      int32     `gorm:"column:appearance;not null" json:"appearance"`
	Morality        int32     `gorm:"column:morality;not null" json:"morality"`
	Affection       int32     `gorm:"column:affection;not null" json:"affection"`
	Personality     string    `gorm:"column:personality;not null" json:"personality"`
	Position        string    `gorm:"column:position" json:"position"`
	AvatarURL       string    `gorm:"column:avatar_url" json:"avatar_url"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
	IsOwned         bool      `gorm:"column:is_owned;not null" json:"is_owned"`
	BuildingHaremID string    `gorm:"column:building_harem_id;not null" json:"building_harem_id"`
	OwnerID         string    `gorm:"column:owner_id;not null" json:"owner_id"`
}

// TableName Woman's table name
func (*Woman) TableName() string {
	return TableNameWoman
}
